# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/trance/MySQLConnectionPool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/trance/MySQLConnectionPool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trance/MySQLConnectionPool/CMakeFiles /home/trance/MySQLConnectionPool//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trance/MySQLConnectionPool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MySQLConnectionPool

# Build rule for target.
MySQLConnectionPool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MySQLConnectionPool
.PHONY : MySQLConnectionPool

# fast build rule for target.
MySQLConnectionPool/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectionPool.dir/build.make CMakeFiles/MySQLConnectionPool.dir/build
.PHONY : MySQLConnectionPool/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

src/ConnectionPool.o: src/ConnectionPool.cc.o
.PHONY : src/ConnectionPool.o

# target to build an object file
src/ConnectionPool.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectionPool.dir/build.make CMakeFiles/MySQLConnectionPool.dir/src/ConnectionPool.cc.o
.PHONY : src/ConnectionPool.cc.o

src/ConnectionPool.i: src/ConnectionPool.cc.i
.PHONY : src/ConnectionPool.i

# target to preprocess a source file
src/ConnectionPool.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectionPool.dir/build.make CMakeFiles/MySQLConnectionPool.dir/src/ConnectionPool.cc.i
.PHONY : src/ConnectionPool.cc.i

src/ConnectionPool.s: src/ConnectionPool.cc.s
.PHONY : src/ConnectionPool.s

# target to generate assembly for a file
src/ConnectionPool.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectionPool.dir/build.make CMakeFiles/MySQLConnectionPool.dir/src/ConnectionPool.cc.s
.PHONY : src/ConnectionPool.cc.s

src/MySQLConn.o: src/MySQLConn.cc.o
.PHONY : src/MySQLConn.o

# target to build an object file
src/MySQLConn.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectionPool.dir/build.make CMakeFiles/MySQLConnectionPool.dir/src/MySQLConn.cc.o
.PHONY : src/MySQLConn.cc.o

src/MySQLConn.i: src/MySQLConn.cc.i
.PHONY : src/MySQLConn.i

# target to preprocess a source file
src/MySQLConn.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectionPool.dir/build.make CMakeFiles/MySQLConnectionPool.dir/src/MySQLConn.cc.i
.PHONY : src/MySQLConn.cc.i

src/MySQLConn.s: src/MySQLConn.cc.s
.PHONY : src/MySQLConn.s

# target to generate assembly for a file
src/MySQLConn.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectionPool.dir/build.make CMakeFiles/MySQLConnectionPool.dir/src/MySQLConn.cc.s
.PHONY : src/MySQLConn.cc.s

test/test.o: test/test.cc.o
.PHONY : test/test.o

# target to build an object file
test/test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cc.o
.PHONY : test/test.cc.o

test/test.i: test/test.cc.i
.PHONY : test/test.i

# target to preprocess a source file
test/test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cc.i
.PHONY : test/test.cc.i

test/test.s: test/test.cc.s
.PHONY : test/test.s

# target to generate assembly for a file
test/test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cc.s
.PHONY : test/test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MySQLConnectionPool"
	@echo "... test"
	@echo "... src/ConnectionPool.o"
	@echo "... src/ConnectionPool.i"
	@echo "... src/ConnectionPool.s"
	@echo "... src/MySQLConn.o"
	@echo "... src/MySQLConn.i"
	@echo "... src/MySQLConn.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

